server:
  port: 9999
  servlet:
    context-path: /university
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydatabase:Mode=PostgreSQL
    username: sa
    password:
  jpa:
    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
